# Generated by Django 5.0 on 2024-10-11 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contabilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descicao', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('gastos', models.IntegerField()),
                ('credito', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Rh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('genero', models.CharField(choices=[('masculino', 'M'), ('feminino', 'F')], max_length=10)),
                ('provincias', models.CharField(choices=[('Luanda', 'L'), ('Benguela', 'B'), ('Lubango', 'LB'), ('Soyo', 'S'), ('Cabinda', 'C')], max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('nif', models.IntegerField()),
                ('data', models.DateField()),
                ('nacionalidade', models.CharField(max_length=50)),
                ('telefone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('serialnumber', models.IntegerField()),
                ('data', models.DateField()),
            ],
        ),
    ]
